name = "AWK"
grammar = "awk"
path_suffixes = ["awk"]
first_line_pattern = "^#!.*\\bg?awk\\b"
line_comments = ["# "]
brackets = [
    { start = "[", end = "]", close = true, newline = false },
    { start = "(", end = ")", close = true, newline = false },
    { start = "{", end = "}", close = true, newline = false },
    { start = "\"", end = "\"", close = true, newline = false, not_in = [
        "comment",
        "string",
    ] },
    { start = "'", end = "'", close = true, newline = false, not_in = [
        "comment",
        "string",
    ] },
]

# Indent if the line ends with an opening bracket.
increase_indent_pattern = "[(\\[{]\\s*$"

# Dedent if the line starts with a closing bracket.
decrease_indent_pattern = "^\\s*[\\)\\]}]"
